
exports.START_QUIZ = "START_QUIZ";
exports.START_QUIZ_SUCCESS = "START_QUIZ_SUCCESS";
exports.START_QUIZ_ERROR = "START_QUIZ_ERROR";
exports.SUBMIT_QUIZ = "SUBMIT_QUIZ";

exports.QUIT_QUIZ = "QUIT_QUIZ";

exports.SELECT_ANSWER = "SELECT_ANSWER";

exports.NEXT_QUEST = "NEXT_QUEST";